[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "About"
pageRef = "about"
weight = 10

[[main]]
name = "Research"
pageRef = "research"
weight = 20

[[main]]
name = "Publications"
pageRef = "publications"
weight = 30

[[main]]
name = "Projects"
pageRef = "projects"
weight = 35

[[main]]
name = "Teaching"
pageRef = "teaching"
weight = 40

[[main]]
name = "Team"
pageRef = "team"
weight = 45

[[main]]
name = "Join"
pageRef = "openings"
weight = 50

[[main]]
name = "Activities"
pageRef = "activities"
weight = 60


[[main]]
name = "Contact"
pageRef = "contact"
weight = 65


[[main]]
name = "CV"
url = "/files/cv.pdf"
weight = 70