colorScheme = "slate"

logo = "images/iitb-logo.png"
disableTextInHeader = false

defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
customCSS = ["css/custom.css"]

mainSections = ["posts"]

[homepage]
layout = "background"

[header]
layout = "basic"

[footer]
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true