baseURL = "https://ashishpalresearch.github.io/ashish-pal-website/"
languageCode = "en"
title = "RISE Lab"
theme = "blowfish"

[pagination]
pagerSize = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true